export const StatusCode = {
  FAIL: 100,
  NEED_REDIRECT: 301,
  FORBIDDEN: 403,
  RESOURCE_NOT_FOUND: 404,
  INTERNAL_ERROR: 500,
  PARAMETER_INVALID: 600,
  PARAMETER_CANT_BE_EMPTY: 601,
  NEED_USER_LOGIN: 602,
  ILLEGAL_PROTOCOL: 603,
  SIGNATURE_EXPIRED: 610,
  SIGNATURE_INVALID: 611,
  ACCESS_ID_INVALID: 612,
  DO_NOT_HAVE_ANY_MORE_RECORD: 700,
  IS_HAVE_THE_SAVE_RECORD: 701,
  LINK_INVALID: 705,
  NOT_ALLOW_UPSHELF_APP: 720,

  VALIDATE_USERNAME_FAIL: 800,
  VALIDATE_PHONE_FAIL: 801,
  VALIDATE_COMMOM_CODE_ERROR: 802,
  ACCOUNT_USERNAME_PASSWORD_FAIL: 803,
  ACCOUNT_LOGIN_NEED_GRAPHIC_VERIFICATION: 804,
  LOGIN_THREE_TIMES_WARNING: 805,
  LOGIN_TWO_TIMES_WARNING: 806,
  LOGIN_ONE_TIMES_WARNING: 807,
  INTELLIGENT_VERIFY_FAIL: 808,
  ACCOUNT_LOCKED: 809,
  VERIFICATION_CODE_SEND_FORBIDDEN: 810,
  VALIDATE_CODE_ERROR: 811,
  ACCOUNT_PHONE_BIND_FAIL: 812,
  ACCOUNT_OLD_PASSWORD_ERROR: 813,
  FILE_DELETE_SUCCESS: 900,
  
  APPSECRET_NOT_CORRECT: 1000,
  APPSECRET_EXPIRED: 1001,
  EXIST_SAME_ZIP: 1002,

  APP_OFF_SHELF: 1003,
  APP_BEEN_DELETED: 1004,
  APPSECRET_NOT_VALID: 1005,
  APP_AUDIT_STATUS_IS_ERROR: 1006,
  CONSUMER_MODEL_SETTING_ERROR: 1018,
  RESOURCES_FULL: 1019,
  no_real_name_verification: 1020,
  audit_app_is_running: 1022,
  TOKEN_NOT_EXIST: 1101,
  NOT_IDLE_TOKEN: 1102,
  NICKNAME_EXIST: 1103,

  AMOUNT_NOT_ENOUGH: 2100,
  CAST_SCREEN_RUNNING: 3001,
  CAST_SCREEN_NOT_RUN: 3002,
  CAST_SCREEN_PWD_ERROR: 3003,
  CAST_SCREEN_CONCURRENCY_EXCEEDED: 3004,
  CAST_SCREEN_PWD_SAME: 3005,
  CAST_SCREEN_SDK_NOT_SUPPORT: 3006,
};

export const StatusMap = new Map([
  [StatusCode.FAIL, "失败"],
  [StatusCode.NEED_REDIRECT, "需要跳转地址"],
  [StatusCode.FORBIDDEN, "没有权限"],
  [StatusCode.RESOURCE_NOT_FOUND, "平台暂无可用资源，请稍后再试"],
  [StatusCode.INTERNAL_ERROR, "服务器处理失败"],
  [StatusCode.PARAMETER_INVALID, "非法参数"],
  [StatusCode.PARAMETER_CANT_BE_EMPTY, "缺少必要参数"],
  [StatusCode.NEED_USER_LOGIN, "需要用户登录"],
  [StatusCode.ILLEGAL_PROTOCOL, "非法请求"],
  [StatusCode.SIGNATURE_EXPIRED, "签名过期"],
  [StatusCode.SIGNATURE_INVALID, "非法签名"],
  [StatusCode.ACCESS_ID_INVALID, "非法鉴权"],
  [StatusCode.DO_NOT_HAVE_ANY_MORE_RECORD, "链接不存在"],
  [StatusCode.IS_HAVE_THE_SAVE_RECORD, "已存在相同记录"],
  [StatusCode.LINK_INVALID, "该链接已不存在"],
  [StatusCode.NOT_ALLOW_UPSHELF_APP, "没有上架权限"],
  [StatusCode.VALIDATE_USERNAME_FAIL, "用户名已存在"],
  [StatusCode.VALIDATE_PHONE_FAIL, "手机号已存在"],
  [StatusCode.VALIDATE_COMMOM_CODE_ERROR, "验证码不正确，请重新输入"],
  [StatusCode.ACCOUNT_USERNAME_PASSWORD_FAIL, "账号或密钥输入不正确"],
  [StatusCode.ACCOUNT_LOGIN_NEED_GRAPHIC_VERIFICATION, "需要图形验证码验证"],
  [StatusCode.LOGIN_THREE_TIMES_WARNING, "您还剩余三次机会"],
  [StatusCode.LOGIN_TWO_TIMES_WARNING, "您还剩余二次机会"],
  [
    StatusCode.LOGIN_ONE_TIMES_WARNING,
    "您只剩余一次机会，若忘记密钥，可尝试找回密钥",
  ],
  [StatusCode.INTELLIGENT_VERIFY_FAIL, "智能验证失败"],
  [
    StatusCode.ACCOUNT_LOCKED,
    "您的账号已被冻结！如有疑问，请拨打电话400-8037-298",
  ],
  [
    StatusCode.VERIFICATION_CODE_SEND_FORBIDDEN,
    "验证码发送次数过多，请明天再试",
  ],
  [StatusCode.VALIDATE_CODE_ERROR, "验证码不正确，请重新输入"],
  [StatusCode.ACCOUNT_PHONE_BIND_FAIL, "该手机号未绑定账户"],
  [StatusCode.ACCOUNT_OLD_PASSWORD_ERROR, "旧密钥不正确，请重新输入"],
  [StatusCode.APPSECRET_NOT_CORRECT, "访问密钥错误"],
  [StatusCode.APPSECRET_EXPIRED, "链接已过期"],
  [StatusCode.EXIST_SAME_ZIP, "存在相同的应用程序包"],
  [StatusCode.FILE_DELETE_SUCCESS, "删除成功"],
  [StatusCode.APP_OFF_SHELF, "应用已下架"],
  [StatusCode.APP_BEEN_DELETED, "应用已删除"],
  [StatusCode.APPSECRET_NOT_VALID, "链接未生效"],
  [StatusCode.APP_AUDIT_STATUS_IS_ERROR, "应用未审核通过"],
  [StatusCode.CONSUMER_MODEL_SETTING_ERROR, "资源不足"],
  [StatusCode.RESOURCES_FULL, "当前资源已被占满，请稍后再试"],
  [StatusCode.AMOUNT_NOT_ENOUGH, "余额不足，请充值后再打开应用"],
  [StatusCode.CAST_SCREEN_RUNNING, "投屏正在运行"],
  [StatusCode.CAST_SCREEN_NOT_RUN, "主控端未开启"],
  [StatusCode.CAST_SCREEN_PWD_ERROR, "口令错误"],
  [StatusCode.CAST_SCREEN_CONCURRENCY_EXCEEDED, "当前投屏端进入人数已满"],
  [StatusCode.CAST_SCREEN_PWD_SAME, "该口令已被创建使用"],
  [StatusCode.CAST_SCREEN_SDK_NOT_SUPPORT, "暂不支持sdk访问投屏链接"],

  [StatusCode.TOKEN_NOT_EXIST, "token不存在"],
  [StatusCode.NOT_IDLE_TOKEN, "投屏端数量已到达上限"],
  [StatusCode.NICKNAME_EXIST, "昵称已存在"],
  [StatusCode.no_real_name_verification, "需进行实名认证后，才能访问应用。"],
  [StatusCode.audit_app_is_running, "正在审核中"],
]);
