export const StatusCode = {
  FAIL: 100,
  RESOURCE_NOT_FOUND: 404,
  INTERNAL_ERROR: 500,
  PARAMETER_INVALID: 600,
  LINK_INVALID: 705,

  APPSECRET_NOT_CORRECT: 1000,
  APPSECRET_EXPIRED: 1001,
  APP_OFF_SHELF: 1003,
  APP_BEEN_DELETED: 1004,
  APPSECRET_NOT_VALID: 1005,
  APP_AUDIT_STATUS_IS_ERROR: 1006,
  CONSUMER_MODEL_SETTING_ERROR: 1018,
  RESOURCES_FULL: 1019,
  no_real_name_verification: 1020,
  audit_app_is_running: 1022,
  app_not_synced: 1035,
  LOCAL_STORAGE_NOT_DISTRIBUTED: 1044,
  TOKEN_NOT_EXIST: 1101,
  NOT_IDLE_TOKEN: 1102,
  NICKNAME_EXIST: 1103,

  AMOUNT_NOT_ENOUGH: 2100,
  CAST_SCREEN_RUNNING: 3001,
  CAST_SCREEN_NOT_RUN: 3002,
  CAST_SCREEN_PWD_ERROR: 3003,
  CAST_SCREEN_CONCURRENCY_EXCEEDED: 3004,
  CAST_SCREEN_PWD_SAME: 3005,
  CAST_SCREEN_SDK_NOT_SUPPORT: 3006,
};

export const StatusMap = new Map([
  [StatusCode.FAIL, "失败"],
  [StatusCode.RESOURCE_NOT_FOUND, "平台暂无可用资源，请稍后再试"],
  [StatusCode.INTERNAL_ERROR, "服务器处理失败"],
  [StatusCode.PARAMETER_INVALID, "非法参数"],
  [StatusCode.LINK_INVALID, "该链接已不存在"],

  [StatusCode.APPSECRET_NOT_CORRECT, "访问密钥错误"],
  [StatusCode.APPSECRET_EXPIRED, "链接已过期"],
  [StatusCode.APP_OFF_SHELF, "应用已下架"],
  [StatusCode.APP_BEEN_DELETED, "应用已删除"],
  [StatusCode.APPSECRET_NOT_VALID, "链接未生效"],
  [StatusCode.APP_AUDIT_STATUS_IS_ERROR, "应用未审核通过"],
  [StatusCode.CONSUMER_MODEL_SETTING_ERROR, "资源不足"],
  [StatusCode.RESOURCES_FULL, "当前资源已被占满，请稍后再试"],
  [StatusCode.AMOUNT_NOT_ENOUGH, "余额不足，请充值后再打开应用"],
  [StatusCode.CAST_SCREEN_RUNNING, "投屏正在运行"],
  [StatusCode.CAST_SCREEN_NOT_RUN, "主控端未开启"],
  [StatusCode.CAST_SCREEN_PWD_ERROR, "口令错误"],
  [StatusCode.CAST_SCREEN_CONCURRENCY_EXCEEDED, "当前投屏端进入人数已满"],
  [StatusCode.CAST_SCREEN_PWD_SAME, "该口令已被创建使用"],
  [StatusCode.CAST_SCREEN_SDK_NOT_SUPPORT, "暂不支持sdk访问投屏链接"],

  [StatusCode.TOKEN_NOT_EXIST, "token不存在"],
  [StatusCode.NOT_IDLE_TOKEN, "投屏端数量已到达上限"],
  [StatusCode.NICKNAME_EXIST, "昵称已存在"],
  [StatusCode.no_real_name_verification, "需进行实名认证后，才能访问应用。"],
  [StatusCode.audit_app_is_running, "正在审核中"],
  [StatusCode.app_not_synced, "共享存储未同步完成"],
  [StatusCode.LOCAL_STORAGE_NOT_DISTRIBUTED, "本地存储未同步完成"],
]);
